name: test
on: [push]
jobs:
  Run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run test
        run: | 
          pip install pytest
          pytest

      - name: build
        run: docker build -t testynov .

      - name: run
        run: docker run -t testynov
